// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	filters: {
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		methods: {
			/**
			 * o​r
			 */
			or: string
			/**
			 * a​n​d
			 */
			and: string
			/**
			 * n​o​t
			 */
			not: string
		}
		entities: {
			/**
			 * P​e​r​s​o​n
			 */
			person: string
			/**
			 * P​e​r​f​o​r​m​e​r
			 */
			performer: string
			/**
			 * W​o​r​k
			 */
			work: string
			/**
			 * C​o​r​p​o​r​a​t​i​o​n
			 */
			corporation: string
			/**
			 * L​o​c​a​t​i​o​n
			 */
			location: string
			/**
			 * P​e​r​f​o​r​m​a​n​c​e​s
			 */
			performances: string
			/**
			 * C​o​m​p​o​s​e​r
			 */
			composer: string
			/**
			 * S​o​u​r​c​e
			 */
			source: string
		}
		filter: {
			/**
			 * s​h​o​w​ ​t​h​e​ ​'​o​r​'​ ​e​v​e​n​t​s​ ​a​s​ ​p​e​r​f​o​r​m​a​n​c​e​s​ ​i​n​ ​t​h​e​ ​g​r​a​p​h
			 */
			checkboxPerformanceEvent: string
			/**
			 * b​o​t​h​ ​c​o​m​p​o​s​e​r​ ​a​n​d​ ​p​e​r​f​o​r​m​e​r
			 */
			makeItBothComposerAndPerformer: string
			/**
			 * a​s​ ​a
			 */
			asA: string
		}
	}
	graphs: {
		/**
		 * L​i​n​e
		 */
		line: string
		/**
		 * M​a​p
		 */
		map: string
		/**
		 * P​i​e
		 */
		pie: string
		/**
		 * T​a​b​l​e
		 */
		tab: string
	}
	events: {
		/**
		 * S​h​o​w​ ​a​l​l​ ​p​e​r​f​o​r​m​a​n​c​e​s
		 */
		showAllPerformances: string
		/**
		 * P​e​r​f​o​r​m​e​d​ ​b​y
		 */
		performedBy: string
		settings: {
			/**
			 * S​e​t​t​i​n​g​s
			 */
			title: string
			/**
			 * S​h​o​w​ ​m​o​r​e​ ​o​p​t​i​o​n​s​ ​o​n​ ​f​i​l​t​e​r​ ​o​v​e​r
			 */
			showMoreOptionsOnFilterOver: string
			/**
			 * S​h​o​w​ ​e​v​e​n​t​ ​a​s​ ​m​o​d​a​l
			 */
			showEventAsModal: string
		}
	}
	navbar: {
		/**
		 * M​e​n​u
		 */
		menu: string
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * D​a​t​a​b​a​s​e
		 */
		database: string
		/**
		 * E​x​h​i​b​i​t​i​o​n​s
		 */
		exhibitions: string
	}
	commons: {
		/**
		 * Y​e​a​r
		 */
		year: string
		/**
		 * H​i
		 */
		hallo: string
		/**
		 * e​n​-​G​B
		 */
		codeLang: string
	}
	admin: {
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
		/**
		 * P​r​e​v​i​e​w
		 */
		preview: string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * A​d​d​ ​n​e​w​ ​e​x​h​i​b​i​t​i​o​n
		 */
		addNewExhibition: string
		/**
		 * C​r​e​a​t​e​ ​n​e​w​ ​e​x​h​i​b​i​t​i​o​n
		 */
		createNewExhibition: string
		/**
		 * M​o​d​i​f​y​ ​e​x​h​i​b​i​t​i​o​n
		 */
		modifyExhibition: string
		/**
		 * T​i​t​l​e
		 */
		title: string
		/**
		 * n​o​ ​l​a​n​g
		 */
		noLang: string
		/**
		 *  ​-​ ​p​u​b​l​i​s​h​e​d
		 */
		publishedSuffix: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * P​u​b​l​i​s​h
		 */
		publish: string
		/**
		 * U​n​p​u​b​l​i​s​h
		 */
		unpublish: string
		/**
		 * R​e​v​e​r​t​ ​t​o​ ​p​u​b​l​i​s​h​e​d
		 */
		revertToPublished: string
		/**
		 * T​a​k​e​ ​o​v​e​r​ ​e​d​i​t​i​n​g
		 */
		takeOverEditing: string
		/**
		 * n​o​t​ ​p​u​b​l​i​s​h​e​d​ ​y​e​t
		 */
		notPublishedYet: string
		/**
		 * l​a​s​t​ ​p​u​b​l​i​s​h
		 */
		lastPublish: string
		/**
		 * l​a​s​t​ ​s​a​v​e
		 */
		lastSave: string
		/**
		 * E​d​i​t​i​n​g​ ​b​y
		 */
		editingBy: string
		/**
		 * D​e​l​e​t​e​ ​t​h​i​s​ ​e​x​h​i​b​i​t​i​o​n​ ​a​n​d​ ​a​l​l​ ​i​t​s​ ​f​i​l​e​s​?​ ​T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
		 */
		deleteConfirm: string
		/**
		 * D​e​l​e​t​i​n​g​…
		 */
		deleting: string
		/**
		 * E​r​r​o​r​ ​d​e​l​e​t​i​n​g​ ​e​x​h​i​b​i​t​i​o​n
		 */
		errorDeleting: string
		/**
		 * E​-​M​a​i​l
		 */
		email: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * m​a​i​l​@​e​x​a​m​p​l​e​.​c​o​m
		 */
		emailPlaceholder: string
		/**
		 * p​a​s​s​w​o​r​d
		 */
		passwordPlaceholder: string
	}
}

export type TranslationFunctions = {
	filters: {
		/**
		 * Search
		 */
		search: () => LocalizedString
		methods: {
			/**
			 * or
			 */
			or: () => LocalizedString
			/**
			 * and
			 */
			and: () => LocalizedString
			/**
			 * not
			 */
			not: () => LocalizedString
		}
		entities: {
			/**
			 * Person
			 */
			person: () => LocalizedString
			/**
			 * Performer
			 */
			performer: () => LocalizedString
			/**
			 * Work
			 */
			work: () => LocalizedString
			/**
			 * Corporation
			 */
			corporation: () => LocalizedString
			/**
			 * Location
			 */
			location: () => LocalizedString
			/**
			 * Performances
			 */
			performances: () => LocalizedString
			/**
			 * Composer
			 */
			composer: () => LocalizedString
			/**
			 * Source
			 */
			source: () => LocalizedString
		}
		filter: {
			/**
			 * show the 'or' events as performances in the graph
			 */
			checkboxPerformanceEvent: () => LocalizedString
			/**
			 * both composer and performer
			 */
			makeItBothComposerAndPerformer: () => LocalizedString
			/**
			 * as a
			 */
			asA: () => LocalizedString
		}
	}
	graphs: {
		/**
		 * Line
		 */
		line: () => LocalizedString
		/**
		 * Map
		 */
		map: () => LocalizedString
		/**
		 * Pie
		 */
		pie: () => LocalizedString
		/**
		 * Table
		 */
		tab: () => LocalizedString
	}
	events: {
		/**
		 * Show all performances
		 */
		showAllPerformances: () => LocalizedString
		/**
		 * Performed by
		 */
		performedBy: () => LocalizedString
		settings: {
			/**
			 * Settings
			 */
			title: () => LocalizedString
			/**
			 * Show more options on filter over
			 */
			showMoreOptionsOnFilterOver: () => LocalizedString
			/**
			 * Show event as modal
			 */
			showEventAsModal: () => LocalizedString
		}
	}
	navbar: {
		/**
		 * Menu
		 */
		menu: () => LocalizedString
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Database
		 */
		database: () => LocalizedString
		/**
		 * Exhibitions
		 */
		exhibitions: () => LocalizedString
	}
	commons: {
		/**
		 * Year
		 */
		year: () => LocalizedString
		/**
		 * Hi
		 */
		hallo: () => LocalizedString
		/**
		 * en-GB
		 */
		codeLang: () => LocalizedString
	}
	admin: {
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * Preview
		 */
		preview: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Add new exhibition
		 */
		addNewExhibition: () => LocalizedString
		/**
		 * Create new exhibition
		 */
		createNewExhibition: () => LocalizedString
		/**
		 * Modify exhibition
		 */
		modifyExhibition: () => LocalizedString
		/**
		 * Title
		 */
		title: () => LocalizedString
		/**
		 * no lang
		 */
		noLang: () => LocalizedString
		/**
		 *  - published
		 */
		publishedSuffix: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Publish
		 */
		publish: () => LocalizedString
		/**
		 * Unpublish
		 */
		unpublish: () => LocalizedString
		/**
		 * Revert to published
		 */
		revertToPublished: () => LocalizedString
		/**
		 * Take over editing
		 */
		takeOverEditing: () => LocalizedString
		/**
		 * not published yet
		 */
		notPublishedYet: () => LocalizedString
		/**
		 * last publish
		 */
		lastPublish: () => LocalizedString
		/**
		 * last save
		 */
		lastSave: () => LocalizedString
		/**
		 * Editing by
		 */
		editingBy: () => LocalizedString
		/**
		 * Delete this exhibition and all its files? This cannot be undone.
		 */
		deleteConfirm: () => LocalizedString
		/**
		 * Deleting…
		 */
		deleting: () => LocalizedString
		/**
		 * Error deleting exhibition
		 */
		errorDeleting: () => LocalizedString
		/**
		 * E-Mail
		 */
		email: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * mail@example.com
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * password
		 */
		passwordPlaceholder: () => LocalizedString
	}
}

export type Formatters = {}
